"""Geometric wire generation for inter-block connections.

No A*, no path search, no collision grid.  Each wire is a single orthogonal
bend between two pin positions.  Bend direction is chosen by:
  1. Rectangle overlap check (avoid component bodies)
  2. Prefer horizontal-then-vertical for left→right signals
  3. Prefer vertical-then-horizontal for power (top→bottom)

Intra-block wires are already generated by the expander.
This module handles only inter-block wires.
"""

from __future__ import annotations

import math
from typing import Any, Optional

from agent.schematic.schematic_types import WireSegment


def _pin_sheet_position(ctx: Any, pin_key: str) -> Optional[tuple[float, float]]:
    """Calculate the absolute sheet position of a pin.

    pin_key format: "REF_DES:pin_number"
    Returns (x, y) in millimeters.
    """
    if ":" not in pin_key:
        return None
    ref = pin_key.split(":")[0]
    comp_positions = ctx.metadata.get("component_positions", {})
    comp_pos = comp_positions.get(ref)
    if comp_pos is None:
        return None

    cx, cy, rot = comp_pos
    graph = ctx.synthesis_graph
    if graph is None:
        return (cx, cy)

    # Get pin's internal position from synthesis graph
    comp = graph.components.get(ref)
    if comp is None:
        return (cx, cy)

    pin = comp.pins.get(pin_key)
    if pin is None:
        return (cx, cy)

    px, py = getattr(pin, "position", (0.0, 0.0))
    # Apply component rotation
    if abs(rot) > 0.001:
        rad = math.radians(rot)
        cos_r = math.cos(rad)
        sin_r = math.sin(rad)
        rx = px * cos_r - py * sin_r
        ry = px * sin_r + py * cos_r
        px, py = rx, ry

    return (cx + px, cy + py)


def _choose_bend(
    src: tuple[float, float],
    tgt: tuple[float, float],
    is_power: bool = False,
    bboxes: Optional[list[tuple[float, float, float, float]]] = None,
) -> tuple[tuple[float, float], tuple[float, float], tuple[float, float]]:
    """Choose a single bend point and return (src, bend, tgt).

    Two candidates:
      A: horizontal then vertical  (mid_x=tgt.x, mid_y=src.y)
      B: vertical then horizontal  (mid_x=src.x, mid_y=tgt.y)

    Picks the one with fewer bbox overlaps.
    """
    sx, sy = src
    tx, ty = tgt

    if abs(sx - tx) < 0.001 or abs(sy - ty) < 0.001:
        return (src, src, tgt)

    bend_a = (tx, sy)
    bend_b = (sx, ty)

    if bboxes is None or not bboxes:
        if is_power or ty > sy:
            return (src, bend_b, tgt)
        return (src, bend_a, tgt)

    def _segment_overlaps_bbox(p1, p2, bbox):
        bx, by, bw, bh = bbox
        min_x, max_x = min(p1[0], p2[0]), max(p1[0], p2[0])
        min_y, max_y = min(p1[1], p2[1]), max(p1[1], p2[1])
        return not (max_x < bx or min_x > bx + bw or max_y < by or min_y > by + bh)

    overlaps_a = 0
    for bb in bboxes:
        if _segment_overlaps_bbox(src, bend_a, bb):
            overlaps_a += 1
        if _segment_overlaps_bbox(bend_a, tgt, bb):
            overlaps_a += 1

    overlaps_b = 0
    for bb in bboxes:
        if _segment_overlaps_bbox(src, bend_b, bb):
            overlaps_b += 1
        if _segment_overlaps_bbox(bend_b, tgt, bb):
            overlaps_b += 1

    if overlaps_a < overlaps_b:
        return (src, bend_a, tgt)
    return (src, bend_b, tgt)


def _build_block_component_map(ctx: Any) -> dict[str, set[str]]:
    """Map each block ID to the set of component ref_des it contains."""
    bg = ctx.block_graph
    if bg is None:
        return {}
    mapping: dict[str, set[str]] = {}
    for bid, block in bg.blocks.items():
        mapping[bid] = set(block.all_components())
    return mapping


def _build_component_block_map(ctx: Any) -> dict[str, str]:
    """Map each component ref_des to its block ID."""
    bg = ctx.block_graph
    if bg is None:
        return {}
    mapping: dict[str, str] = {}
    for bid, block in bg.blocks.items():
        for ref in block.all_components():
            mapping[ref] = bid
    return mapping


def generate_wires(ctx: Any) -> list[WireSegment]:
    """Generate inter-block wires for all nets in the circuit.

    For each net, finds components from different blocks that share
    the net, and generates a single-bend orthogonal wire between them.

    Results are stored in ctx.metadata["inter_block_wires"] and ctx.wires.
    """
    graph = ctx.synthesis_graph
    if graph is None:
        return []

    comp_block = _build_component_block_map(ctx)
    existing_wires = list(ctx.metadata.get("intra_block_wires", []))
    new_wires: list[WireSegment] = []
    seen: set[tuple[str, str, str]] = set()

    # Build bboxes for all placed components (for overlap avoidance)
    comp_positions = ctx.metadata.get("component_positions", {})
    bboxes: list[tuple[float, float, float, float]] = []
    for ref, (x, y, _rot) in comp_positions.items():
        bboxes.append((x - 5, y - 5, 10, 10))

    for net in graph.nets.values():
        net_pins = net.pins
        if not net_pins:
            continue

        net_name = net.name
        is_power = str(net.role.value) in ("power", "ground") if hasattr(net.role, "value") else False

        # Group pins by block
        pins_by_block: dict[str, list[str]] = {}
        for pk in net_pins:
            ref = pk.split(":")[0] if ":" in pk else ""
            bid = comp_block.get(ref)
            if bid:
                if bid not in pins_by_block:
                    pins_by_block[bid] = []
                pins_by_block[bid].append(pk)

        if len(pins_by_block) < 2:
            continue

        # Generate wires between consecutive blocks
        block_ids = list(pins_by_block.keys())
        for i in range(len(block_ids) - 1):
            bid_a = block_ids[i]
            bid_b = block_ids[i + 1]
            pk_a = pins_by_block[bid_a][0]
            pk_b = pins_by_block[bid_b][0]

            edge_key = (tuple(sorted([pk_a, pk_b])), net_name, "")
            if edge_key in seen:
                continue
            seen.add(edge_key)

            pos_a = _pin_sheet_position(ctx, pk_a)
            pos_b = _pin_sheet_position(ctx, pk_b)
            if pos_a is None or pos_b is None:
                continue

            src, bend, tgt = _choose_bend(pos_a, pos_b, is_power, bboxes)
            raw_points = [src, bend, tgt]
            points = _deduplicate_points(raw_points)

            new_wires.append(WireSegment(
                source=pk_a,
                target=pk_b,
                net=net_name,
                points=points,
                width_mm=0.254,
            ))

    all_wires = existing_wires + new_wires
    ctx.wires = all_wires
    ctx.metadata["inter_block_wires"] = new_wires
    return all_wires


def _deduplicate_points(
    points: list[tuple[float, float]],
) -> list[tuple[float, float]]:
    """Remove consecutive duplicate points."""
    if not points:
        return []
    result = [points[0]]
    for p in points[1:]:
        if abs(p[0] - result[-1][0]) > 0.001 or abs(p[1] - result[-1][1]) > 0.001:
            result.append(p)
    return result
